export enum CheckoutRoutes {
  ROOT = "",
  DONA = "dona",
  LEGGI_CODICE_QR = "leggi-codice-qr",
  INSERISCI_DATI_AVVISO = "inserisci-dati-avviso",
  DATI_PAGAMENTO = "dati-pagamento",
  INSERISCI_EMAIL = "inserisci-email",
  INSERISCI_CARTA = "inserisci-carta",
  SCEGLI_METODO = "scegli-metodo",
  RIEPILOGO_PAGAMENTO = "riepilogo-pagamento",
  CARRELLO = "c",
  ESITO = "esito",
  ANNULLATO = "annullato",
  ERRORE = "errore",
}
